on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.7
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
      - name: Build
        run: |
          zig build
