on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.7
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: master
      - name: Build
        run: |
          zig build
